### PR TITLE
next version of chickencurry

### PR DESCRIPTION
**Pull request by stoeffel**
:warning: NOT READY YET :warning: 
Todo
- [ ] add more tests
- [ ] rename repo to `curry-this`
- [ ] link to trine by @jussi-kalliokoski

### CODE REVIEW

**Comment by stoeffel** [comment]
I created a PR, to make discussing things easier.

**Comment by tomekwi** [comment]
Haha, funny, I started working on the thing exactly at the same time! Good thing I started with tests and you with the implementation. I’ll have a look in a moment.

**Comment by stoeffel** [comment]
:smiley_cat:

**Comment by tomekwi** [comment]
Alright, let me push my stuff and then we’ll take away what we don’t need.

**Comment by tomekwi** [comment]
@stoeffel it looks like you wrote tests for the ES5 API and I wrote them for the ES6 one :) Not bad :)

My tests fail however and I haven’t had the time to see why. I can come back to it tomorrow. See you then!

**Comment by stoeffel** [comment]
:-) want have time tonight either. See you tomorrow.

**Comment by tomekwi** [comment]
By the way, I’ve just noticed chickencurry is at v2 at the moment. So I’ve moved this all to *v3*.

**Pull request closed without merging**
