### PR TITLE
A brand new chickencurry

### PR DESCRIPTION
**Pull request by tomekwi**
Continuation of #12

### CODE REVIEW

**Comment by stoeffel** [comment]
IMO this is almost good to go. I will rename the repo after merge. 
What say @tomekwi? Did we miss something?

**Comment by stoeffel** [comment]
@tomekwi IMO this is good to go now. Would be cool if you would have a final look at it (if you find some time).

**Comment by tomekwi** [comment]
Hi @stoeffel I added another spec ( https://github.com/stoeffel/chickencurry/commit/5ebd84ce5209e1f83142c7df25818f72e9a8a4c1 ) and satisfied it. Turned out not to be a trivial thing. Some more reading:

* http://stackoverflow.com/a/7317057/2816199
* https://github.com/blakeembrey/arity/blob/6feb5344baace182493cc30f2fa45d06e31dd61a/arity.js

**Comment by tomekwi** [comment]
Some finishing touches and I think it’s good to go.

> I added another spec ( 5ebd84c ) and satisfied it

We get explicitness and better interoperability with other tools – at the cost of a dependency. What do you say?

**Comment by stoeffel** [comment]
I think to have one dep, which probably will never changes is okay. Thanks for finishing it up. btw. I created a module to handle arity too https://github.com/stoeffel/arityN. But with a different approach and it only works for functions with less then 6 args.

I will merge and publish later today....

Thanks again for your awesome work.

**Pull request merged**
